core-files: Add missing directories and initialize them
managarm/bootstrap-managarm pull request #147
Opened 2021-11-27 22:49 UTC by Dennisbonke

This PR fixes some strange errors during boot relating to mount failures.

2021-11-28 08:12 UTC, avdgrinten reviewed
Why is /boot/grub created unconditionally? Shouldn't grub create that at installation time? (And if GRUB is not installed, it should not be needed.)

2021-11-28 12:15 UTC, Dennisbonke commented
I've just replicated the directories from update-image.py, it seems to be created unconditionally there too.

2021-12-04 17:50 UTC, ArsenArsen requested changes
I'm not sure how to handle home and such. Maybe making home is fine while we hardcode passwd?

2021-12-04 17:50 UTC, ArsenArsen commented on bootstrap.yml
> +      - args: ['touch', '@THIS_COLLECT_DIR@/home/managarm/.keep']
likewise

2021-12-04 17:50 UTC, ArsenArsen commented on bootstrap.yml
>        - args: ['mkdir', '-p', '@THIS_COLLECT_DIR@/home/managarm']
out of scope for packages

2021-12-07 09:36 UTC, avdgrinten commented
We can probably keep hardcoding /home/managarm for now.

2022-04-04 01:15 UTC, Dennisbonke commented
As requested, the grub directories are no longer there. As the consensus is that we can continue hardcoding `/home/managarm` for now, this should be good to go now.

2022-04-04 06:10 UTC, ArsenArsen commented
sure, but no packages should contain anything in /home, especially considering we'll remove it.
it's better to create/remove this dir when making an image IMHO.

2022-04-16 14:02 UTC, Dennisbonke commented
> sure, but no packages should contain anything in /home, especially considering we'll remove it. it's better to create/remove this dir when making an image IMHO.

Eventually we should probably remove that yeah, instead putting common dotfiles in `/etc/skel` and letting `useradd` handle it. For now, this should be fine tho.

2022-04-16 14:53 UTC, avdgrinten approved these changes

2022-04-16 14:53 UTC, merged