rust: port alacritty
managarm/bootstrap-managarm pull request #180
Opened 2022-05-15 19:31 UTC by 64

Ports the required libraries for alacritty, including some bits of nix and mio.

Blocked on a number of PRs:
- [ ] https://github.com/managarm/managarm/pull/447
- [ ] https://github.com/managarm/managarm/pull/448
- [ ] https://github.com/managarm/mlibc/pull/429
- [ ] https://github.com/managarm/libasync/pull/15

2022-05-26 14:33 UTC, Dennisbonke requested changes
Some small things here and there, patches look fine to me.

2022-05-26 14:33 UTC, Dennisbonke commented on bootstrap.d/x11-terms.yml
> +      tag: 'v0.10.0'
Version 0.10.1 is out, we should upgrade if possible.

2022-05-26 14:33 UTC, Dennisbonke commented on bootstrap.d/x11-terms.yml
> +    pkgs_required:
Gentoo also lists freetype and wayland as dependencies, do we need those too?

2022-06-06 19:46 UTC, Dennisbonke reviewed
LGTM but some questions I'd like answers to before merging.

2022-06-06 19:50 UTC, 64 commented on patches/rust-libc/0003-managarm-alacritty-updates.patch
> ++        pub c_cc: [::cc_t; NCCS],
See managarm/mlibc#430. This should still be fine to merge since none of our Rust ports use this currently.

2022-06-06 19:50 UTC, 64 commented on patches/rust-libc/0003-managarm-alacritty-updates.patch
> ++pub type sa_family_t = ::c_int;
no

2022-06-06 19:57 UTC, Dennisbonke approved these changes
LGTM now

2022-06-06 20:06 UTC, merged