bootstrap.yml: install cxxshim and frigg headers to /usr/share
managarm/bootstrap-managarm pull request #182
Opened 2022-05-20 19:40 UTC by 64

As discussed on Discord. This allows cxxshim and frigg to be found via `pkg-config` rather than needing to do `ln` hacks.

Some things may break if they incorrectly use frigg without declaring it as a dependency, see e.g https://github.com/managarm/managarm/pull/453.

2022-05-21 14:09 UTC, ArsenArsen commented
why not /usr/include/$name instead?

2022-05-21 17:38 UTC, 64 commented
> why not /usr/include/$name instead?

cc @avdgrinten

2022-05-21 17:45 UTC, avdgrinten commented
That's even more confusing since the path to the headers is then `/usr/include/$name/$name`.

2022-05-22 00:33 UTC, 64 commented
maybe as a compromise, we could install to `/usr/include/freestanding/$name`?

2022-05-22 06:20 UTC, ArsenArsen commented
well that'd only be necessary for cxxshim right? Frigg doesn't conflict with anything, and hence could reside globally?

2022-05-22 07:28 UTC, avdgrinten commented
In principle yes, but doing it for all freestanding libs has the advantage that we cannot accidentally include non-freestanding headers.

I would still prefer installing to `/usr/share` instead of `/usr/include/freestanding`. We could symlinks `/usr/include/$name` to `/usr/share/$name/include/$name` but that would only be useful for build systems that do not use pkg-config anyway.

2022-05-22 12:36 UTC, avdgrinten commented
We should also consider adding `--wrap-mode=nofallback` to the Meson packages that do not use the "symlinked subproject" hack anymore.

2022-05-22 21:51 UTC, Dennisbonke requested changes
Other than the change @avdgrinten requested, looks good to me. My comments are minor and I can live without them, tho the metadata thing really should be fixed.

2022-05-22 21:51 UTC, Dennisbonke commented on bootstrap.yml
> +    labels: [aarch64]
While insignificant, we can probably add risc-v as a label here too.

2022-05-22 21:51 UTC, Dennisbonke commented on bootstrap.yml
> +    architecture: '@OPTION:arch@'
Headers only, thus arch independent? Mark as noarch in that case.

2022-05-22 21:51 UTC, Dennisbonke commented on bootstrap.yml
> +        # Install to /usr/share to avoid conflicts with standard C++ headers.
Going to put it here, but the same comments from cxxshim apply for frigg, while we’re working on it, we can fix it, saves us fixing later.

2022-05-22 21:51 UTC, Dennisbonke commented on bootstrap.yml
> +  - name: cxxshim
Missing metadata, please add it. We should add missing metadata whenever we’re updating a package. I guess the maintainer of both frigg and cxxshim would be @avdgrinten?

2022-05-22 22:41 UTC, 64 commented
Blocker: I've just noticed that `host-managarm-tools` also requires frigg headers, but there's no straightforward way to satisfy that requirement now that we don't symlink frigg like we did before.

2022-05-29 20:06 UTC, avdgrinten commented
Can this be merged now?

2022-05-29 20:07 UTC, 64 commented
Should be good to go

2022-05-29 20:07 UTC, merged

2022-05-29 20:07 UTC, avdgrinten commented
Thank you!