Xwayland fix and wayland stack version bumps
managarm/bootstrap-managarm pull request #209
Opened 2022-09-28 18:39 UTC by no92

2022-09-28 19:14 UTC, Dennisbonke approved these changes
LGTM

2022-09-28 19:16 UTC, Dennisbonke requested changes
You need to reset the revision on wayland and wayland-protocols and bump the revision on xorg-server

2022-09-29 07:48 UTC, ArsenArsen requested changes

2022-09-29 07:48 UTC, ArsenArsen commented on bootstrap.d/dev-libs.yml
>        - wayland-scanner
this shouldn't be revision 2 after the bump

2022-09-29 16:22 UTC, no92 commented
Addressed the comments raised above and updated `xorg-server` and split out `xwayland`.

2022-10-07 17:43 UTC, no92 commented
Reordered and re-signed the commits.

2022-10-10 10:07 UTC, no92 commented
Included a bump to weston and included weston's new dependency on seatd in order to resolve Xwayland issues.

2022-10-10 14:23 UTC, Dennisbonke requested changes
Some small things that need to be fixed but overall this PR looks nice.

2022-10-10 14:23 UTC, Dennisbonke commented on bootstrap.d/dev-libs.yml
>      revision: 3
The revision needs to be removed as we're upgrading versions.

2022-10-10 14:23 UTC, Dennisbonke commented on bootstrap.d/dev-libs.yml
> +      - seatd
We should replace the dependency on `xorg-server` with `xwayland`.

2022-10-10 14:23 UTC, Dennisbonke commented on bootstrap.d/x11-base.yml
> +  - name: xwayland
Missing metadata, feel free to add it if you feel like maintaining this part of the Xorg stack. If you rather have me maintain it, let me know and I'll take it.

2022-10-10 14:23 UTC, Dennisbonke commented on bootstrap.d/x11-libs.yml
> +  - name: libxcvt
Missing metadata, feel free to add it if you feel like maintaining this part of the Xorg stack. If you rather have me maintain it, let me know and I'll take it.
Also, you're missing the `labels: [aarch64]` thing, as it stands this build _will_ fail on xbbs for aarch64.

2022-10-10 16:08 UTC, Dennisbonke requested changes
Two minor nitpicks, other than that looks good.

2022-10-10 16:08 UTC, Dennisbonke commented on bootstrap.d/x11-base.yml
> +    metadata:
Wrong location, other ports put metadata above the source declaration. For consistency's sake we should do the same here.

2022-10-10 16:08 UTC, Dennisbonke commented on bootstrap.d/x11-libs.yml
> +    metadata:
Wrong location, other ports put metadata above the source declaration. For consistency's sake we should do the same here.

2022-10-10 16:16 UTC, no92 commented
Rebased, fixed up the fixups and addressed the comments above.

2022-10-10 16:24 UTC, Dennisbonke approved these changes
LGTM, thanks for the PR!

2022-10-10 16:25 UTC, merged