Rust toolchain updates
managarm/bootstrap-managarm pull request #228
Opened 2023-02-22 01:12 UTC by Dennisbonke

This PR updates the rust toolchain to 1.67.1, which is currently the latest version. It should also fix `xbbs` for the cargo problem. Tested with `exa`, `alacritty` is still broken, and I'll look into that later.

2023-02-22 23:56 UTC, Dennisbonke commented
Alacritty is no longer broken at build time, but we're running into pthread issues at runtime. Something to look into later. For now, let's re-enable `alacritty` on the ci.

2023-02-26 22:01 UTC, 64 requested changes

2023-02-26 22:01 UTC, 64 commented on patches/rust-nix/0001-managarm-initial-port.patch
> ++    #[repr(i64)]
This is not really a robust change, but something we'll have to deal with when we upstream :^)

2023-03-06 19:39 UTC, no92 commented on patches/rust-libc/0004-managarm-More-additions-for-a-newer-nix-version.patch
> ++        pub sigev_notify: ::c_int,
I honestly fail to see where this is wrong.

2023-03-06 19:45 UTC, 64 commented on patches/rust-libc/0004-managarm-More-additions-for-a-newer-nix-version.patch
> ++        pub sigev_notify: ::c_int,
Aren't signo and notify the wrong way around?

2023-03-06 19:46 UTC, 64 commented on patches/rust-libc/0004-managarm-More-additions-for-a-newer-nix-version.patch
> ++        pub sigev_notify: ::c_int,
And the member below is missing too

2023-03-06 19:51 UTC, Dennisbonke commented on patches/rust-libc/0004-managarm-More-additions-for-a-newer-nix-version.patch
> ++        pub sigev_notify: ::c_int,
Yeah they are the wrong way around. I'll swap them. How would I do that last member in rust? I'm not sure how to do that.

2023-03-06 20:16 UTC, ikbenlike commented on patches/rust-libc/0004-managarm-More-additions-for-a-newer-nix-version.patch
> ++        pub sigev_notify: ::c_int,
```rust
sigev_notify_function: fn(sigval) -> *c_void
```

probably? I'm no rust guru though

2023-03-06 20:56 UTC, Dennisbonke commented on patches/rust-libc/0004-managarm-More-additions-for-a-newer-nix-version.patch
> ++        pub sigev_notify: ::c_int,
@64 should be fixed, ready for review.

2023-03-06 21:44 UTC, 64 approved these changes

2023-03-06 21:47 UTC, merged