Update to Weston 12
managarm/bootstrap-managarm pull request #244
Opened 2023-07-24 15:50 UTC by no92

2023-07-24 19:10 UTC, Dennisbonke requested changes
LGTM, two issues.

2023-07-25 19:06 UTC, Dennisbonke commented
A bunch of unrelated files are now part of this PR?

2023-07-26 07:13 UTC, no92 commented
Fixed.

2023-07-26 21:58 UTC, Dennisbonke approved these changes
LGTM

2023-07-26 21:58 UTC, merged