Add support for generating docs
managarm/bootstrap-managarm pull request #260
Opened 2023-10-02 12:47 UTC by no92

2023-10-06 22:19 UTC, Dennisbonke requested changes
Two items that will break xbbs otherwise. Outside that, LGTM

2023-10-06 22:19 UTC, Dennisbonke commented on bootstrap.yml
> +  - name: host-xxd
Missing labels and the architecture field.

2023-10-06 22:19 UTC, Dennisbonke commented on bootstrap.yml
> +  - name: host-hdoc
Missing labels and the architecture field.

2023-10-07 00:23 UTC, no92 commented
Addressed the issues raised.

2023-10-07 13:39 UTC, Dennisbonke approved these changes
LGTM

2023-10-07 13:39 UTC, merged