Small update batch
managarm/bootstrap-managarm pull request #282
Opened 2023-11-02 14:45 UTC by no92

2023-11-02 15:37 UTC, Dennisbonke requested changes
One comment

2023-11-02 15:37 UTC, Dennisbonke commented on bootstrap.d/dev-libs.yml
> +      maintainer: "no92 <no92.mail@gmail.com>"
Use your @managarm.org address here too.

2023-11-02 15:38 UTC, no92 commented on bootstrap.d/dev-libs.yml
> +      maintainer: "no92 <no92.mail@gmail.com>"
Done.

2023-11-09 12:45 UTC, Dennisbonke approved these changes
LGTM

2023-11-09 12:46 UTC, merged