libgcc: Enable decimal float support for AArch64
managarm/bootstrap-managarm pull request #300
Opened 2024-02-05 19:46 UTC by Qwinci

Enable decimal float support on AArch64 libgcc. This patch should probably be upstreamed to gcc at some point too.

2024-02-05 21:23 UTC, ArsenArsen commented
we have a gcc fork at managarm/gcc that we use - please send a PR there (see comment in other PR, I didn't see this notification before commenting - my bad)

2024-02-06 08:06 UTC, Qwinci commented
> we have a gcc fork at managarm/gcc that we use - please send a PR there (see comment in other PR, I didn't see this notification before commenting - my bad)

I opened a PR there and modified this one to just bump the revisions.

2024-02-06 09:16 UTC, no92 approved these changes
LGTM once managarm/gcc#1 is merged.

2024-02-06 09:37 UTC, Qwinci commented
I guess this also needs a tag bump on the gcc repository and in this PR, Ill modify this one when the gcc PR gets merged and a new tag is created.

2024-02-06 13:11 UTC, Dennisbonke requested changes
LGTM but please drop the revisions from the gcc package and the gcc tools.

2024-02-06 13:19 UTC, ArsenArsen reviewed
missclick - sorry

lgtm, reset revision though

2024-02-06 13:24 UTC, qookei approved these changes

2024-02-06 13:25 UTC, Dennisbonke approved these changes
LGTM

2024-02-06 13:47 UTC, merged