managarm-system: use `mold` instead of `ld`
managarm/bootstrap-managarm pull request #351
Opened 2024-06-12 19:38 UTC by no92

2024-06-12 19:55 UTC, no92 commented
Depends on managarm/managarm#683.

2024-06-14 11:54 UTC, ArsenArsen commented
(not against the change.. in fact, i have already messed with mold before, just curious)

what's the reason for this change?

2024-06-14 12:33 UTC, ElectrodeYT commented
> (not against the change.. in fact, i have already messed with mold before, just curious)
> 
> what's the reason for this change?

It's quite a bit faster, and reduces iteration time by a decent amount, especially on slower machines, if a change is made that requires relinking several servers or other binaries.

2024-08-20 18:27 UTC, Dennisbonke requested changes
One issue

2024-08-20 18:27 UTC, Dennisbonke commented on bootstrap.d/sys-devel.yml
> +  - name: host-mold
I miss the label tag (if applicable) and the architecture flag. Can you add them?

2024-08-21 08:18 UTC, no92 commented
Fixed the issue and rebased onto master.

2024-08-21 22:35 UTC, Dennisbonke approved these changes
LGTM

2024-08-21 22:40 UTC, merged