Bump linux-headers, iproute2
managarm/bootstrap-managarm pull request #354
Opened 2024-06-12 20:15 UTC by no92

2024-08-20 18:29 UTC, Dennisbonke requested changes
Two issues

2024-08-20 18:29 UTC, Dennisbonke commented on bootstrap.d/sys-apps.yml
> +      version: '6.9.0'
You need to reset the revision field

2024-08-20 18:29 UTC, Dennisbonke commented on bootstrap.d/sys-apps.yml
> +      git: 'https://github.com/iproute2/iproute2.git'
Why the change from git.kernel.org? Isn't git.kernel.org the actual upstream?

2024-08-21 08:16 UTC, no92 commented
Fixed the issues and rebased onto master.

2024-08-21 22:38 UTC, Dennisbonke approved these changes
LGTM

2024-08-21 22:42 UTC, merged